# Generated by Django 4.2 on 2023-05-03 12:46

from django.db import migrations, models
import musics.validators


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='music',
            old_name='Album',
            new_name='album',
        ),
        migrations.RenameField(
            model_name='music',
            old_name='artist',
            new_name='artiste',
        ),
        migrations.AlterField(
            model_name='album',
            name='name',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='music',
            name='audio_file',
            field=models.FileField(upload_to='musics/', validators=[musics.validators.validate_is_audio]),
        ),
        migrations.AlterField(
            model_name='music',
            name='cover_image',
            field=models.ImageField(upload_to='music_images/'),
        ),
    ]
